const { Router } = require("express");
const express=require("express");
const {getAllCustomers,createCustomer,updateCustomer,deleteCustomer, loginCustomer}=require("../controllers/customerController");
const { isAuthenticatedClient } = require("../middleware/auth");
const router=express.Router();
console.log("Route start point");
router.route("/customers").get(isAuthenticatedClient, getAllCustomers);
router.route("/customers/new").post(createCustomer);
router.route("/customers/:id").put(updateCustomer).delete(deleteCustomer);
module.exports=router;